"""create tables

Revision ID: 2c8396fd1831
Revises: 
Create Date: 2024-09-22 15:21:22.924881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8396fd1831'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('founding_year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('operation_size', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producers'))
    )
    op.create_table('cheeses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producer_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('is_raw_milk', sa.Boolean(), nullable=True),
    sa.Column('production_date', sa.DateTime(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], name=op.f('fk_cheeses_producer_id_producers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cheeses'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cheeses')
    op.drop_table('producers')
    # ### end Alembic commands ###
